'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace StoreRepInDB.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As StoreRepInDB.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New StoreRepInDB.Properties.Settings())), StoreRepInDB.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return StoreRepInDB.Properties.Settings.defaultInstance
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString)>
        <Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\ReportsDB.mdb;Persis" & "t Security Info=True")>
        Public ReadOnly Property ReportsDBConnectionString As String
            Get
                Return(CStr((Me("ReportsDBConnectionString"))))
            End Get
        End Property
    End Class
End Namespace
